easy_admin:

  site_name: '<i class="fa fa-balance-scale"></i> Processo Jurídico'

  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'
    number: 'R$ %.2f'

  list:
    title: 'Lista de %%entity_label%%'
    actions:
      - { name: 'show', label: '', icon: 'search' }
      - { name: 'edit', label: '', icon: 'edit' }
      - { name: 'delete', label: '', icon: 'trash' }

  design:

    form_theme: 'vertical'

    color_scheme: 'dark'

    brand_color: '#e01d25'

    assets:
      favicon:
        path: 'bundles/easyadmin/img/balance.png'
        mime_type: 'image/png'

    menu:
      - { entity: 'Processo', label: 'Processos', icon: 'gavel', default: true }
      - label: "Cadastros"
        icon: 'plus-square'
        children:
          - { entity: 'Comarca', label: 'Comarcas', icon: 'institution'}
          - { entity: 'Vara', label: 'Varas', icon: 'home'}
          - { entity: 'Classificacao', label: 'Classificações', icon: 'sort-amount-desc' }
          - { entity: 'Motivo', label: 'Motivos', icon: 'question-circle' }
          - { entity: 'Situacao', label: 'Situações', icon: 'stack-exchange' }
          - { entity: 'TipoDocumento', label: 'Tipos de Documento', icon: 'address-card' }
          - { entity: 'Uf', label: 'UFs', icon: 'globe' }
          - { entity: 'Pessoa', label: 'Pessoas', icon: 'user-circle'}
          - { entity: 'Filial', label: 'Filiais', icon: 'sitemap'}
          - { entity: 'Usuario', label: 'Usuários', icon: 'user'}

  entities:

    Processo:
      class: App\Entity\Processo
      label: "Processos"
      show:
        max_results: 20

      list:
        max_results: 30
        fields:
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara' }
          - { property: 'requerentes', label: 'Requerentes' }
          - { property: 'requeridos', label: 'Requeridos' }
          - { property: 'situacao', label: 'Situação' }
          - { property: 'valorCausa', label: 'Valor da causa'}
          - { property: 'criadoEm', label: 'Data de criação', format: 'd/m/Y' }
          - { property: 'filial.numero', label: 'Filial' }
          - { property: 'isEnviadoNuvem', label: 'Nuvem', type: 'boolean' }

        sort: ['criadoEm', 'desc']

      form:
        fields:
          - { type: 'group', css_class: 'col-sm-12', label: 'Processo' }
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara' }
          - { property: 'valorCausa', label: 'Valor da Causa', type: 'money', type_options: { currency: 'BRL' }  }
          - { type: 'group', css_class: 'col-sm-12', label: 'Envolvidos' }
          - { property: 'requerentes', label: 'Requerentes' }
          - { property: 'requeridos', label: 'Requeridos' }
          - { type: 'group', css_class: 'col-sm-12', label: 'Adicionais' }
          - { property: 'filial', label: 'Filial' }
          - { property: 'situacao', label: 'Situação' }
          - { property: 'usuarioCriacao', label: 'Usuário' }

    Vara:
      class: App\Entity\Comarca\Vara
      label: "Varas"
      list:
        fields: ['comarca','nome']

    Comarca:
      class: App\Entity\Comarca
      label: "Comarcas"
      list:
        fields: ['uf','nome', 'varas']

    Uf:
      class: App\Entity\Uf
      label: "UFs"
      list:
        fields: ['sigla','nome']
        sort: ['sigla', 'asc']

    Situacao:
      class: App\Entity\Situacao
      label: "Situações"
      list:
        fields: ['nome','descricao']

    Classificacao:
      class: App\Entity\Classificacao
      label: "Classificações"
      list:
        fields:
          - 'nome'
          - { property: 'provisao', label: 'Provisão' }

    Motivo:
      class: App\Entity\Motivo
      label: "Motivos"
      list:
        fields: ['nome', 'descricao']

    Pessoa:
      class: App\Entity\Pessoa
      label: "Pessoas"
      list:
        fields: ['tipo_documento', 'documento', 'nome']

    TipoDocumento:
      class: App\Entity\TipoDocumento
      label: "Tipos de Documentos"
      list:
        fields: ['nome']

    Usuario:
      class: App\Entity\Usuario
      label: "Usuários"
      list:
        fields: ['login', 'nome', 'ativo']

    Filial:
      class: App\Entity\Filial
      label: "Filial"