easy_admin:

  site_name: "<img src='https://png.icons8.com/metro/1600/batman-new.png' /> Processo <i>Jurídico</i>"

  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'

  assets:
    favicon: 'bundles/easyadmin/img/batman.ico'

  design:

    color_scheme: 'dark'
    brand_color: '#1ABC9C'

    menu:
      - { entity: 'Processo', label: 'Processos', icon: 'gavel' }
      - label: "Comarcas"
        icon: 'plus-square'
        children:
          - { entity: 'Comarca', label: 'Comarcas', icon: 'institution'}
          - { entity: 'Vara', label: 'Varas', icon: 'home'}
      - label: "Cadastros"
        icon: 'plus-square'
        children:
          - { entity: 'Uf', label: 'UFs', icon: 'globe' }
          - { entity: 'Classificacao', label: 'Classificações', icon: 'sort-amount-desc' }
          - { entity: 'Motivo', label: 'Motivos', icon: 'commenting' }

  entities:
    Vara:
      class: App\Entity\Comarca\Vara
      label: "Varas"
      list:
        title: 'Lista de %%entity_label%%'
        fields: ['comarca','nome']

    Comarca:
      class: App\Entity\Comarca
      label: "Comarcas"
      list:
        title: 'Lista de %%entity_label%%'
        fields: ['uf','nome']

    Uf:
      class: App\Entity\Uf
      label: "UFs"
      list:
        title: 'Lista de %%entity_label%%'
        fields: ['sigla','nome']
      show:
        title: '%%entity_label%% (#%%entity_id%%) nome'

    Situacao:
      class: App\Entity\Situacao
      label: "Situações"

    Classificacao:
      class: App\Entity\Classificacao
      label: "Classificações"

    Processo:
      class: App\Entity\Processo
      label: "Processos"

    Motivo:
      class: App\Entity\Motivo
      label: "Motivos"

    Pessoa:
      class: App\Entity\Pessoa
      label: "Pessoas"

    TipoDocumento:
      class: App\Entity\TipoDocumento
      label: "Tipos de Documentos"