easy_admin:

  site_name: '<i class="fa fa-balance-scale"></i> Processo Jurídico'

  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'
    number: '%.2f'

  list:
    title: 'Lista de %%entity_label%%'
    actions:
      - { name: 'show', label: '', icon: 'search' }
      - { name: 'edit', label: '', icon: 'edit' }
      - { name: 'delete', label: '', icon: 'trash' }

  assets:
    favicon: 'bundles/easyadmin/img/batman.ico'

  design:

    color_scheme: 'dark'
    brand_color: '#1ABC9C'

    menu:
      - { entity: 'Processo', label: 'Processos', icon: 'gavel' }
      - label: "Comarcas/Varas"
        icon: 'plus-square'
        children:
          - { entity: 'Comarca', label: 'Comarcas', icon: 'institution'}
          - { entity: 'Vara', label: 'Varas', icon: 'home'}
      - label: "Cadastros"
        icon: 'plus-square'
        children:
          - { entity: 'Classificacao', label: 'Classificações', icon: 'sort-amount-desc' }
          - { entity: 'Motivo', label: 'Motivos', icon: 'question-circle' }
          - { entity: 'Situacao', label: 'Situações', icon: 'stack-exchange' }
          - { entity: 'TipoDocumento', label: 'Tipos de Documento', icon: 'address-card' }
          - { entity: 'Uf', label: 'UFs', icon: 'globe' }

  entities:
    Vara:
      class: App\Entity\Comarca\Vara
      label: "Varas"
      list:
        fields: ['comarca','nome']

    Comarca:
      class: App\Entity\Comarca
      label: "Comarcas"
      list:
        fields: ['uf','nome', 'varas']

    Uf:
      class: App\Entity\Uf
      label: "UFs"
      list:
        fields: ['sigla','nome']
        sort: ['sigla', 'asc']

    Situacao:
      class: App\Entity\Situacao
      label: "Situações"
      list:
        fields: ['nome','descricao']

    Classificacao:
      class: App\Entity\Classificacao
      label: "Classificações"
      list:
        fields:
          - 'nome'
          - { property: 'provisao', label: 'Provisão' }

    Processo:
      class: App\Entity\Processo
      label: "Processos"

    Motivo:
      class: App\Entity\Motivo
      label: "Motivos"
      list:
        fields: ['nome', 'descricao']

    Pessoa:
      class: App\Entity\Pessoa
      label: "Pessoas"

    TipoDocumento:
      class: App\Entity\TipoDocumento
      label: "Tipos de Documentos"
      list:
        fields: ['nome']