easy_admin:

    site_name: "<img src='https://png.icons8.com/metro/1600/batman-new.png' /> Processo <i>Jurídico</i>"

    design:

        color_scheme: 'light'

        assets:
            favicon: 'bundles/easyadmin/img/batman.ico'
    entities:
        Motivo:
            class: App\Entity\Motivo