version: '3'

services:

    db:
        image: mysql:5.7
        container_name: proceso-juridico-db
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306

    app:
        image: ambientum/php:7.2-nginx
        container_name: processo-juridico-app
        volumes:
            - .:/var/www/app
        ports:
            - 8000:8080
        links:
            - db