easy_admin:
  entities:
    Classificacao:
      class: App\Entity\Classificacao
      label: "Classificações"
      form:
        title: "Adicionar/Editar Classificação"
        fields:
          - 'nome'
          - { property: 'provisao', label: 'Provisão' }
      list:
        fields:
          - 'nome'
          - { property: 'provisao', label: 'Provisão' }