easy_admin:
  entities:
    Motivo:
      class: App\Entity\Motivo
      label: "Motivos"
      form:
        title: "Adicionar/Editar Motivo"
        fields:
          - 'nome'
          - { property: 'descricao', label: 'Descriçãoo' }
      list:
        fields:
          - 'nome'
          - { property: 'descricao', label: 'Descriçãoo' }