easy_admin:
  entities:
    Pessoa:
      class: App\Entity\Pessoa
      label: "Pessoas"
      form:
        title: "Adicionar/Editar Pessoa"
        fields: ['tipoDocumento', 'documento', 'nome', 'nomeTratamento']
      list:
        fields: ['tipoDocumento', 'documento', 'nome', 'nomeTratamento', 'processosRequerentes', 'processosRequeridos']