easy_admin:
  entities:
    Processo:
      class: App\Entity\Processo
      label: "Processos"
      show:
        fields:
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara' }
          - { property: 'motivos', label: 'Motivos'}
          - { property: 'valorCausa', label: 'Valor da Causa'}
          - { property: 'requerentes', label: 'Requerentes' }
          - { property: 'requeridos', label: 'Requeridos' }
          - { property: 'getFilialVisualizacao', label: 'Filial'}
          - { property: 'situacao', label: 'Situação' }
      form:
        title: "Adicionar/Editar Processo"
        fields:
          - { type: 'tab' , label: 'Dados do Processo', icon: 'file' }
          - { type: 'group', css_class: 'col-sm-12', label: 'Processo' }
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara', type: 'easyadmin_autocomplete' }
          - { property: 'motivos', label: 'Motivos', type_options: { required: true } }
          - { property: 'valorCausa', label: 'Valor da Causa', type: 'money', type_options: { currency: 'BRL' }  }

          - { type: 'group', css_class: 'col-sm-12', label: 'Envolvidos' }
          - { property: 'requerentes', label: 'Requerentes', type_options: { required: true }, type: 'easyadmin_autocomplete' }
          - { property: 'requeridos', label: 'Requeridos', type_options: { required: true }, type: 'easyadmin_autocomplete' }

          - { type: 'tab' , label: 'Informações Adicionais', icon: 'plus' }
          - { type: 'group', css_class: 'col-sm-6', label: 'Adicionais' }
          - { property: 'filial', label: 'Filial', type: 'easyadmin_autocomplete', help: 'Filial à qual foi aberto o processo' }
          - { property: 'situacao', label: 'Situação' }
      list:
        max_results: 3
        fields:
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara', type_options: { raw: true } }
          - { property: 'criadoEm', label: 'Data de crição', format: 'd/m/Y' }
          - { property: 'situacao', label: 'Situação' }
          - { property: 'valorCausa', label: 'Valor da causa'}
          - { property: 'listaRequerentes', label: 'Requerentes', type: 'array' }
          - { property: 'listaRequeridos', label: 'Requeridos', type: 'array' }
          - { property: 'getFilialVisualizacao', label: 'Filial' }
          - { property: 'isEnviadoNuvem', label: 'Nuvem', type: 'boolean' }

      sort: ['criadoEm', 'desc']