easy_admin:
  entities:
    Processo:
      class: App\Entity\Processo
      label: "Processos"
      show:
        fields:
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara' }
          - { property: 'motivos', label: 'Motivos'}
          - { property: 'situacao', label: 'Situação' }
          - { property: 'requerentes', label: 'Requerentes' }
          - { property: 'requeridos', label: 'Requeridos' }
          - { property: 'getFilialVisualizacao', label: 'Filial'}
          - { property: 'valorCausa', label: 'Valor da Causa'}
          - { property: 'criadoEm', label: 'Criado em'}
          - { property: 'valorSentenca', label: 'Valor da Sentença'}
          - { property: 'ajuizadoEm', label: 'Ajuizado em'}
          - { property: 'valorAcordo', label: 'Valor do Recebimento'}
          - { property: 'recebidoEm', label: 'Recebido em'}

      form:
        title: "Adicionar/Editar Processo"
        fields:
          - { type: 'tab' , label: 'Dados do Processo', icon: 'file' }
          - { type: 'group', css_class: 'col-sm-12', label: 'Processo' }
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara', type: 'easyadmin_autocomplete' }
          - { property: 'motivos', label: 'Motivos', type_options: { required: true } }
          - { property: 'situacao', label: 'Situacao', type_options: { required: true } }

          - { type: 'group', css_class: 'col-sm-12', label: 'Envolvidos' }
          - { property: 'requerentes', label: 'Requerentes', type_options: { required: true }, type: 'easyadmin_autocomplete' }
          - { property: 'requeridos', label: 'Requeridos', type_options: { required: true }, type: 'easyadmin_autocomplete' }
          - { property: 'filial', label: 'Filial', type: 'easyadmin_autocomplete', help: 'Filial à qual foi aberto o processo' }

          - { type: 'group', label: 'Datas e Valores' }
          - { property: 'valorCausa', label: 'Valor da Causa', type: 'money', type_options: { currency: 'BRL' } , css_class: 'col-sm-2' }
          - { property: 'criadoEm', label: 'Aberto em', format: 'd/m/Y', css_class: 'col-sm-2'}

          #- { type: 'group', css_class: 'col-sm-4', label: 'Ajuizamento' }
          - { property: 'valorSentenca', label: 'Valor da Sentença', type: 'money', type_options: { currency: 'BRL' }, css_class: 'col-sm-2'  }
          - { property: 'ajuizadoEm', label: 'Ajuizado Em', format: 'd/m/Y', css_class: 'col-sm-2'  }

          #- { type: 'group', css_class: 'col-sm-4', label: 'Recebimento' }
          - { property: 'valorAcordo',  label: 'Valor do Acordo', type: 'money', type_options: { currency: 'BRL' } , css_class: 'col-sm-2' }
          - { property: 'recebidoEm', label: 'Recebido Em', format: 'd/m/Y', css_class: 'col-sm-2'}

      list:
        max_results: 3
        fields:
          - { property: 'codigo', label: 'Código' }
          - { property: 'vara', label: 'Vara', type_options: { raw: true } }
          - { property: 'criadoEm', label: 'Data de crição', format: 'd/m/Y' }
          - { property: 'situacao', label: 'Situação' }
          - { property: 'valorCausa', label: 'Valor da causa'}
          - { property: 'listaRequerentes', label: 'Requerentes', type: 'array' }
          - { property: 'listaRequeridos', label: 'Requeridos', type: 'array' }
          - { property: 'getFilialVisualizacao', label: 'Filial' }
          - { property: 'isEnviadoNuvem', label: 'Nuvem', type: 'boolean' }

      sort: ['criadoEm', 'desc']