easy_admin:
  entities:
    Situacao:
      class: App\Entity\Situacao
      label: "Situações"
      form:
        title: "Adicionar/Editar Situação"
        fields:
          - 'nome'
          - { property: 'descricao', label: 'Descrição' }
      list:
        fields:
          - 'nome'
          - { property: 'descricao', label: 'Descrição' }